import { CommentatorInfo } from "./schemas/commentor-info.schema";
import { CreateCommentDto } from "../dto/create-comment.dto";

export class Comment {
    constructor(
        public id: string,
        public content: string,
        public commentatorInfo: CommentatorInfo,
        public postId: string,
        public createdAt: Date = new Date(),
        public updatedAt: Date = new Date(),
        public deletedAt: Date | null = null
    ) {}

    makeDeleted(): void {
        this.deletedAt = new Date();
    }

    update(content: string): void {
        this.content = content;
        this.updatedAt = new Date();
    }

    static createInstance(dto: CreateCommentDto): Comment {
        return new Comment(
            '',  // ID will be generated by database
            dto.content,
            new CommentatorInfo(
                dto.commentatorInfo.userId,
                dto.commentatorInfo.userLogin
            ),
            dto.postId
        );
    }
}

// Type exports for compatibility
export type CommentDocument = Comment;
export type CommentModelType = typeof Comment;