import { CreateCommentLikeDto } from "../dto/create-comment-like.dto";

export class CommentLike {
    constructor(
        public id: string,
        public commentId: string,
        public userId: string,
        public status: 'Like' | 'Dislike',
        public createdAt: Date = new Date(),
        public updatedAt: Date = new Date(),
        public deletedAt: Date | null = null
    ) {}

    makeDeleted(): void {
        if (this.deletedAt !== null) {
            throw new Error('Entity already deleted');
        }
        this.deletedAt = new Date();
    }

    updateStatus(status: 'Like' | 'Dislike'): void {
        this.status = status;
        this.updatedAt = new Date();
    }

    static createInstance(dto: CreateCommentLikeDto): CommentLike {
        return new CommentLike(
            '',  // ID will be generated by database
            dto.commentId,
            dto.userId,
            dto.status as 'Like' | 'Dislike'
        );
    }
}

// Type exports for compatibility
export type CommentLikeDocument = CommentLike;
export type CommentLikeModelType = typeof CommentLike;