export class PostLike {
    constructor(
        public id: string,
        public postId: string,
        public userId: string,
        public status: 'Like' | 'Dislike',
        public addedAt: Date,
        public login: string,
        public createdAt: Date = new Date(),
        public updatedAt: Date = new Date(),
        public deletedAt: Date | null = null
    ) {}

    makeDeleted(): void {
        if (this.deletedAt !== null) {
            throw new Error('Entity already deleted');
        }
        this.deletedAt = new Date();
    }

    updateStatus(status: 'Like' | 'Dislike'): void {
        this.status = status;
        this.addedAt = new Date();
        this.updatedAt = new Date();
    }

    static createInstance(postId: string, userId: string, status: 'Like' | 'Dislike', login: string): PostLike {
        return new PostLike(
            '',  // ID will be generated by database
            postId,
            userId,
            status,
            new Date(),
            login
        );
    }
}

// Type exports for compatibility
export type PostLikeDocument = PostLike;
export type PostLikeModelType = typeof PostLike;